# Generated by Django 3.1.1 on 2020-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address_I', models.CharField(max_length=111)),
                ('address_II', models.CharField(blank=True, max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('phone_number', models.CharField(max_length=111)),
            ],
        ),
    ]
