# Generated by Django 3.1.1 on 2020-09-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_I',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_II',
        ),
    ]
