# Generated by Django 3.1.1 on 2020-09-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200907_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='is_topselling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='switch',
            name='is_topselling',
            field=models.BooleanField(default=False),
        ),
    ]
