# Generated by Django 3.1.1 on 2020-10-01 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201002_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
